name: frontend
description: Smart Home Control Application
publish_to: 'none' # Ngăn việc vô tình publish app lên mạng
version: 1.0.0+1

# Khai báo phiên bản SDK (Đoạn này sẽ sửa lỗi bạn vừa gặp)
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_animate: ^4.5.0 # Tạo animation mượt như lụa cực kỳ dễ
  google_fonts: ^6.2.1
  
  flutter:
    sdk: flutter
  
  # Thư viện quản lý trạng thái
  flutter_riverpod: ^2.4.9
  
  # Thư viện giao tiếp mạng
  http: ^1.1.0
  
  # Thư viện giao tiếp thời gian thực
  web_socket_channel: ^3.0.3

  # Cung cấp các icon Material Design
  cupertino_icons: ^1.0.2

  speech_to_text: ^7.3.0
  
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1  # THÊM DÒNG NÀY


# Bật tính năng Material Design 3
flutter:
  uses-material-design: true

# THÊM TOÀN BỘ KHỐI NÀY XUỐNG DƯỚI CÙNG
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/SmartHome.png"
  min_sdk_size: 21